"""PDF generator — WeasyPrint A4 quote PDF per CLAUDE.md § Quote PDF Spec.

Hallmark policy:
  - By default every PDF carries a "Generated by CarpentrIQ" footer hallmark.
  - Pass show_hallmark=False to omit it (requires a paid pdf_credit on the
    carpenter account; enforced by the caller, not here).

Image strategy:
  - All images (carpenter photo, business logo) are downloaded and base64-encoded
    before calling WeasyPrint so rendering never makes outbound HTTP requests.
  - QR code generated in-process via qrcode library.
  - Google Fonts loaded via CSS @import; falls back to Georgia/Arial if unreachable.
"""

from __future__ import annotations

import asyncio
import base64
import io
import logging
from datetime import datetime, timezone
from html import escape

import httpx
import qrcode

from app.config import settings

logger = logging.getLogger(__name__)

FOREST = "#1B3A2D"
GOLD = "#C9A84C"
PARCHMENT = "#F5F0E8"
MIST = "#E8E4DC"
SLATE = "#4A5568"

PDF_CREDIT_PRICE_INR = 99


class PDFGenerator:

    async def generate_quote_pdf(
        self,
        quote: dict,
        carpenter: dict,
        show_hallmark: bool = True,
    ) -> bytes:
        """Render quote as A4 PDF bytes.

        quote      — output of _quote_to_dict() from quote.py
        carpenter  — dict with keys: name, phone, city, photo_url,
                     business_logo_url (optional)
        show_hallmark — False suppresses the CarpentrIQ footer badge
                        (requires a paid credit consumed by the caller)
        """
        photo_b64 = await _download_b64(carpenter.get("photo_url"))
        logo_b64 = await _download_b64(carpenter.get("business_logo_url"))
        share_token = quote.get("share_token", "")
        qr_url = f"{settings.frontend_url}/quote/{share_token}" if share_token else ""
        qr_b64 = _generate_qr_b64(qr_url) if qr_url else ""

        html_src = _build_html(quote, carpenter, photo_b64, logo_b64, qr_b64, show_hallmark)

        from weasyprint import HTML  # lazy import — needs native pango/gobject libs
        pdf_bytes: bytes = await asyncio.get_event_loop().run_in_executor(
            None,
            lambda: HTML(string=html_src).write_pdf(),
        )
        return pdf_bytes

    def _generate_qr(self, url: str) -> bytes:
        buf = io.BytesIO()
        qrcode.make(url).save(buf, format="PNG")
        return buf.getvalue()


# ── HTML builder ──────────────────────────────────────────────────────────────

def _build_html(
    quote: dict,
    carpenter: dict,
    photo_b64: str,
    logo_b64: str,
    qr_b64: str,
    show_hallmark: bool,
) -> str:
    c_name = escape(carpenter.get("name") or "")
    c_phone = escape(carpenter.get("phone") or "")
    c_city = escape(carpenter.get("city") or "")
    q_number = escape(quote.get("quote_number") or "")
    client_name = escape(quote.get("client_name") or "")
    client_phone = escape(quote.get("client_phone") or "")
    notes = escape(quote.get("notes") or "")
    validity_days = quote.get("validity_days") or 7
    created_raw = quote.get("created_at")

    today_str = datetime.now(timezone.utc).strftime("%d %b %Y")
    valid_until_str = _format_valid_until(created_raw, validity_days)

    subtotal = float(quote.get("subtotal") or 0)
    tax = float(quote.get("tax_amount") or 0)
    total = float(quote.get("total_amount") or 0)
    advance = float(quote.get("advance_requested") or 0)
    balance = total - advance

    line_items_html = _build_line_items_html(quote.get("line_items") or [])
    summary_html = _build_summary_html(subtotal, tax, total, advance, balance)
    header_center_html = _build_header_center(c_name, c_phone, c_city, logo_b64)
    hallmark_html = _build_hallmark(qr_b64) if show_hallmark else ""

    photo_html = (
        f'<img class="photo-circle" src="data:image/jpeg;base64,{photo_b64}" alt="">'
        if photo_b64
        else f'<div class="photo-placeholder">{escape(c_name[:1].upper())}</div>'
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=DM+Sans:wght@400;500;600&display=swap');

  * {{ box-sizing: border-box; margin: 0; padding: 0; }}

  body {{
    font-family: 'DM Sans', Arial, sans-serif;
    font-size: 11pt;
    color: {SLATE};
    background: {PARCHMENT};
    padding: 0;
  }}

  .page {{
    width: 210mm;
    min-height: 297mm;
    padding: 14mm 16mm 12mm;
    background: {PARCHMENT};
    display: flex;
    flex-direction: column;
  }}

  /* ── Header ── */
  .header {{
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    border-bottom: 2px solid {FOREST};
    padding-bottom: 10px;
    margin-bottom: 12px;
  }}
  .header-left {{ flex: 0 0 auto; }}
  .header-center {{ flex: 1; text-align: center; padding: 0 12px; }}
  .header-right {{ flex: 0 0 auto; text-align: right; }}

  .brand-name {{
    font-family: 'DM Serif Display', Georgia, serif;
    font-size: 18pt;
    color: {FOREST};
    letter-spacing: -0.3px;
  }}
  .brand-tagline {{ font-size: 7.5pt; color: {GOLD}; letter-spacing: 1px; text-transform: uppercase; }}

  .carpenter-logo {{ max-width: 120px; max-height: 52px; object-fit: contain; margin-bottom: 4px; }}
  .carpenter-name {{ font-size: 13pt; font-weight: 600; color: {FOREST}; }}
  .carpenter-sub {{ font-size: 9pt; color: {SLATE}; }}

  .photo-circle {{
    width: 52px; height: 52px; border-radius: 50%;
    object-fit: cover; border: 2px solid {GOLD};
  }}
  .photo-placeholder {{
    width: 52px; height: 52px; border-radius: 50%;
    background: {FOREST}; color: {GOLD};
    font-size: 20pt; font-family: 'DM Serif Display', Georgia, serif;
    display: flex; align-items: center; justify-content: center;
    border: 2px solid {GOLD};
  }}

  /* ── Meta strip ── */
  .meta-strip {{
    display: flex; gap: 0; border: 1px solid {MIST};
    border-radius: 4px; overflow: hidden; margin-bottom: 14px;
    background: white;
  }}
  .meta-cell {{
    flex: 1; padding: 6px 10px; border-right: 1px solid {MIST};
    font-size: 9pt;
  }}
  .meta-cell:last-child {{ border-right: none; }}
  .meta-label {{ color: {GOLD}; font-size: 7.5pt; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }}
  .meta-value {{ color: {FOREST}; font-weight: 600; margin-top: 2px; }}

  /* ── Scope table ── */
  table.scope {{
    width: 100%; border-collapse: collapse; margin-bottom: 14px; font-size: 9.5pt;
  }}
  table.scope thead th {{
    background: {FOREST}; color: white; padding: 7px 8px;
    text-align: left; font-weight: 600; font-size: 8.5pt; text-transform: uppercase;
    letter-spacing: 0.4px;
  }}
  table.scope thead th:last-child {{ text-align: right; }}
  table.scope tbody tr {{ background: white; }}
  table.scope tbody tr:nth-child(even) {{ background: {PARCHMENT}; }}
  table.scope tbody td {{ padding: 7px 8px; vertical-align: top; border-bottom: 1px solid {MIST}; }}
  table.scope .item-name {{ font-weight: 600; color: {FOREST}; }}
  table.scope .item-spec {{ font-size: 8pt; color: {SLATE}; margin-top: 2px; }}
  table.scope .price-col {{
    text-align: right; white-space: nowrap;
    font-family: 'DM Serif Display', Georgia, serif;
    color: {GOLD}; font-size: 11pt;
  }}

  /* ── Summary ── */
  .summary-wrap {{ display: flex; justify-content: flex-end; margin-bottom: 14px; }}
  table.summary {{
    width: 240px; border-collapse: collapse; font-size: 9.5pt;
  }}
  table.summary td {{ padding: 4px 8px; }}
  table.summary tr.divider td {{ border-top: 1px solid {MIST}; }}
  table.summary tr.total-row td {{
    background: {FOREST}; color: white; font-weight: 600;
    font-family: 'DM Serif Display', Georgia, serif; font-size: 12pt; padding: 6px 8px;
  }}
  table.summary tr.advance-row td {{
    background: {GOLD}; color: white; font-weight: 600; font-size: 9.5pt;
  }}
  table.summary .amount {{ text-align: right; }}

  /* ── Notes ── */
  .notes-box {{
    background: white; border: 1px solid {MIST}; border-radius: 4px;
    padding: 8px 10px; margin-bottom: 14px; font-size: 9pt;
  }}
  .notes-label {{ font-size: 8pt; color: {GOLD}; font-weight: 600; text-transform: uppercase; letter-spacing: 0.4px; margin-bottom: 3px; }}

  /* ── Terms ── */
  .terms {{ font-size: 8pt; color: {SLATE}; margin-bottom: 14px; }}
  .terms-title {{ font-weight: 600; color: {FOREST}; margin-bottom: 4px; }}
  .terms li {{ margin-bottom: 2px; }}

  /* ── Footer ── */
  .footer {{
    margin-top: auto; border-top: 1px solid {MIST};
    padding-top: 8px; display: flex; align-items: center; justify-content: space-between;
  }}
  .qr-block {{ display: flex; align-items: center; gap: 8px; }}
  .qr-block img {{ width: 48px; height: 48px; }}
  .qr-label {{ font-size: 7.5pt; color: {SLATE}; }}
  .hallmark {{
    font-size: 8pt; color: {FOREST}; font-weight: 600; text-align: right;
    border: 1px solid {GOLD}; border-radius: 3px; padding: 4px 8px;
    background: white;
  }}
  .hallmark span {{ color: {GOLD}; }}
</style>
</head>
<body>
<div class="page">

  <!-- HEADER -->
  <div class="header">
    <div class="header-left">
      <div class="brand-name">CarpentrIQ</div>
      <div class="brand-tagline">Professional Quote</div>
    </div>
    <div class="header-center">
      {header_center_html}
    </div>
    <div class="header-right">
      {photo_html}
    </div>
  </div>

  <!-- META STRIP -->
  <div class="meta-strip">
    <div class="meta-cell">
      <div class="meta-label">Quote No.</div>
      <div class="meta-value">{q_number}</div>
    </div>
    <div class="meta-cell">
      <div class="meta-label">Date</div>
      <div class="meta-value">{today_str}</div>
    </div>
    <div class="meta-cell">
      <div class="meta-label">Valid Until</div>
      <div class="meta-value">{valid_until_str}</div>
    </div>
    <div class="meta-cell">
      <div class="meta-label">Client</div>
      <div class="meta-value">{client_name}</div>
    </div>
    <div class="meta-cell" style="border-right:none">
      <div class="meta-label">Phone</div>
      <div class="meta-value">{client_phone}</div>
    </div>
  </div>

  <!-- SCOPE TABLE -->
  <table class="scope">
    <thead>
      <tr>
        <th>#</th>
        <th>Item</th>
        <th>Dimensions</th>
        <th>Material Spec</th>
        <th>Amount (₹)</th>
      </tr>
    </thead>
    <tbody>
      {line_items_html}
    </tbody>
  </table>

  <!-- SUMMARY -->
  {summary_html}

  <!-- NOTES -->
  {f'<div class="notes-box"><div class="notes-label">Notes</div>{notes}</div>' if notes else ''}

  <!-- TERMS -->
  <div class="terms">
    <div class="terms-title">Terms &amp; Conditions</div>
    <ol class="terms">
      <li>This quote is valid for {validity_days} days from the date of issue.</li>
      <li>35% advance payment is required before work commencement; balance due on completion.</li>
      <li>Material prices subject to market rates at time of purchase; final cost may vary by ±5%.</li>
    </ol>
  </div>

  <!-- FOOTER -->
  <div class="footer">
    <div class="qr-block">
      {f'<img src="data:image/png;base64,{qr_b64}" alt="QR">' if qr_b64 else ''}
      <div class="qr-label">Scan to view &amp; approve<br>this quote online</div>
    </div>
    {hallmark_html}
  </div>

</div>
</body>
</html>"""


def _build_header_center(name: str, phone: str, city: str, logo_b64: str) -> str:
    logo_html = (
        f'<img class="carpenter-logo" src="data:image/png;base64,{logo_b64}" alt="logo"><br>'
        if logo_b64 else ""
    )
    return (
        f'{logo_html}'
        f'<div class="carpenter-name">{name}</div>'
        f'<div class="carpenter-sub">+91 {phone} · {city}</div>'
    )


def _build_line_items_html(line_items: list[dict]) -> str:
    rows = []
    for i, item in enumerate(line_items, 1):
        display = escape(item.get("display_name") or item.get("item_type") or "")
        dims = escape(item.get("dimensions_display") or "—")
        spec = _summarise_spec(item.get("material_breakdown") or [])
        price = float(item.get("final_price") or 0)
        rows.append(
            f'<tr>'
            f'<td>{i}</td>'
            f'<td><div class="item-name">{display}</div>'
            f'<div class="item-spec">{spec}</div></td>'
            f'<td style="font-size:8.5pt">{dims}</td>'
            f'<td style="font-size:8.5pt">{spec}</td>'
            f'<td class="price-col">₹{price:,.0f}</td>'
            f'</tr>'
        )
    return "\n".join(rows) if rows else '<tr><td colspan="5">No items</td></tr>'


def _build_summary_html(
    subtotal: float, tax: float, total: float, advance: float, balance: float
) -> str:
    return f"""
<div class="summary-wrap">
  <table class="summary">
    <tr><td>Subtotal</td><td class="amount">₹{subtotal:,.0f}</td></tr>
    {"" if not tax else f'<tr><td>Tax</td><td class="amount">₹{tax:,.0f}</td></tr>'}
    <tr class="divider total-row">
      <td>Total</td><td class="amount">₹{total:,.0f}</td>
    </tr>
    <tr class="advance-row">
      <td>Advance (35%)</td><td class="amount">₹{advance:,.0f}</td>
    </tr>
    <tr class="divider">
      <td>Balance on Completion</td><td class="amount">₹{balance:,.0f}</td>
    </tr>
  </table>
</div>"""


def _build_hallmark(qr_b64: str) -> str:
    return (
        '<div class="hallmark">'
        'Generated by <span>CarpentrIQ</span><br>'
        '<span style="font-size:7pt;color:#888">carpentriq.in</span>'
        '</div>'
    )


def _summarise_spec(breakdown: list[dict]) -> str:
    key_materials = {
        "plywood_bwp_8x4": "BWP Ply",
        "mdf_18mm_8x4": "18mm MDF",
        "laminate_sqft": "Laminate",
        "hinge_softclose": "Soft-close hinges",
        "drawer_slide_bb": "BB drawer slides",
        "hydraulic_lift_mechanism": "Hydraulic lift",
    }
    labels = []
    for item in breakdown:
        name = item.get("name", "")
        if name in key_materials:
            labels.append(key_materials[name])
    return ", ".join(labels[:3]) or "—"


def _format_valid_until(created_raw: str | None, validity_days: int) -> str:
    try:
        from datetime import timedelta
        dt = datetime.fromisoformat(created_raw) if created_raw else datetime.now(timezone.utc)
        return (dt + timedelta(days=validity_days)).strftime("%d %b %Y")
    except Exception:
        return "—"


# ── Image helpers ─────────────────────────────────────────────────────────────

async def _download_b64(url: str | None) -> str:
    """Download image from URL and return base64 string. Returns '' on failure."""
    if not url:
        return ""
    try:
        async with httpx.AsyncClient(timeout=10) as client:
            resp = await client.get(url)
            resp.raise_for_status()
            return base64.b64encode(resp.content).decode()
    except Exception as exc:
        logger.warning("Image download failed for PDF (%s): %s", url, exc)
        return ""


def _generate_qr_b64(url: str) -> str:
    try:
        buf = io.BytesIO()
        qrcode.make(url).save(buf, format="PNG")
        return base64.b64encode(buf.getvalue()).decode()
    except Exception as exc:
        logger.warning("QR generation failed: %s", exc)
        return ""
