"""add_trial_subscription_and_usage_log

Revision ID: 08d17a8bc9f2
Revises: 6b481421f024
Create Date: 2026-04-24 12:05:25.793820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d17a8bc9f2'
down_revision: Union[str, None] = '6b481421f024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carpenter_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('plan_before', sa.Text(), nullable=True),
    sa.Column('plan_after', sa.Text(), nullable=True),
    sa.Column('amount_charged', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('razorpay_payment_id', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carpenter_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('enquiry_id', sa.UUID(), nullable=True),
    sa.Column('cost_to_carpenter', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('carpenters', sa.Column('trial_started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('carpenters', sa.Column('is_trial_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False))
    op.add_column('carpenters', sa.Column('subscription_plan', sa.Text(), server_default='free_trial', nullable=False))
    op.add_column('carpenters', sa.Column('subscription_started_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('carpenters', sa.Column('subscription_expires_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('carpenters', sa.Column('last_payment_date', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('carpenters', sa.Column('next_payment_date', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('carpenters', sa.Column('auto_renew_enabled', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False))
    op.add_column('carpenters', sa.Column('images_used_this_month', sa.Integer(), server_default='0', nullable=False))
    op.add_column('carpenters', sa.Column('images_limit_this_month', sa.Integer(), server_default='20', nullable=False))
    op.add_column('carpenters', sa.Column('quotes_sent_this_month', sa.Integer(), server_default='0', nullable=False))
    op.add_column('carpenters', sa.Column('quotes_sent_limit_this_month', sa.Integer(), server_default='3', nullable=False))
    op.add_column('carpenters', sa.Column('regenerates_used_this_month', sa.Integer(), server_default='0', nullable=False))
    op.add_column('carpenters', sa.Column('regenerates_free_limit', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpenters', 'regenerates_free_limit')
    op.drop_column('carpenters', 'regenerates_used_this_month')
    op.drop_column('carpenters', 'quotes_sent_limit_this_month')
    op.drop_column('carpenters', 'quotes_sent_this_month')
    op.drop_column('carpenters', 'images_limit_this_month')
    op.drop_column('carpenters', 'images_used_this_month')
    op.drop_column('carpenters', 'auto_renew_enabled')
    op.drop_column('carpenters', 'next_payment_date')
    op.drop_column('carpenters', 'last_payment_date')
    op.drop_column('carpenters', 'subscription_expires_at')
    op.drop_column('carpenters', 'subscription_started_at')
    op.drop_column('carpenters', 'subscription_plan')
    op.drop_column('carpenters', 'is_trial_active')
    op.drop_column('carpenters', 'trial_started_at')
    op.drop_table('usage_log')
    op.drop_table('subscription_history')
    # ### end Alembic commands ###
