"""add business_logo_url and pdf_credits_remaining

Revision ID: 4a048ec62fe3
Revises: ca0e5b6fb2f9
Create Date: 2026-04-20 15:39:38.739284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a048ec62fe3'
down_revision: Union[str, None] = 'ca0e5b6fb2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpenters', sa.Column('business_logo_url', sa.Text(), nullable=True))
    op.add_column('carpenters', sa.Column('pdf_credits_remaining', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpenters', 'pdf_credits_remaining')
    op.drop_column('carpenters', 'business_logo_url')
    # ### end Alembic commands ###
