"""add_balance_payment_link_to_jobs

Revision ID: 6b481421f024
Revises: 4a048ec62fe3
Create Date: 2026-04-21 14:03:29.527122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b481421f024'
down_revision: Union[str, None] = '4a048ec62fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('balance_payment_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'balance_payment_link')
    # ### end Alembic commands ###
