"""add_saved_designs

Revision ID: ad9e6f751b04
Revises: f7e2a1b3c8d9
Create Date: 2026-05-05 12:49:24.434785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad9e6f751b04'
down_revision: Union[str, None] = 'f7e2a1b3c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_designs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carpenter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('generated_image_url', sa.Text(), nullable=False),
    sa.Column('selected_style', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('material_grade', sa.Text(), nullable=False),
    sa.Column('room_type', sa.Text(), nullable=True),
    sa.Column('furniture_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_designs_carpenter_id'), 'saved_designs', ['carpenter_id'], unique=False)
    op.alter_column('carpenter_portfolio', 'upload_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('carpenter_portfolio', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('carpenter_reviews', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('carpenter_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('homeowners', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Mumbai'::character varying"))
    op.alter_column('homeowners', 'plan',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'trial'::character varying"))
    op.alter_column('homeowners', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('homeowners_phone_key', 'homeowners', type_='unique')
    op.drop_index('ix_homeowners_phone', table_name='homeowners')
    op.create_index(op.f('ix_homeowners_phone'), 'homeowners', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homeowners_phone'), table_name='homeowners')
    op.create_index('ix_homeowners_phone', 'homeowners', ['phone'], unique=False)
    op.create_unique_constraint('homeowners_phone_key', 'homeowners', ['phone'])
    op.alter_column('homeowners', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('homeowners', 'plan',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'trial'::character varying"))
    op.alter_column('homeowners', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Mumbai'::character varying"))
    op.alter_column('carpenter_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('carpenter_reviews', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('carpenter_portfolio', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('carpenter_portfolio', 'upload_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_saved_designs_carpenter_id'), table_name='saved_designs')
    op.drop_table('saved_designs')
    # ### end Alembic commands ###
