"""initial_schema

Revision ID: ca0e5b6fb2f9
Revises: 
Create Date: 2026-04-20 11:41:42.463866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca0e5b6fb2f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpenters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('whatsapp_number', sa.Text(), nullable=True),
    sa.Column('speciality', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('razorpay_subscription_id', sa.Text(), nullable=True),
    sa.Column('trial_ends_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('quote_link_slug', sa.Text(), nullable=True),
    sa.Column('total_quotes_sent', sa.Integer(), nullable=False),
    sa.Column('total_revenue_processed', sa.NUMERIC(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('quote_link_slug')
    )
    op.create_table('furniture_catalogue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('glb_model_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_type')
    )
    op.create_table('material_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_type', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('price_inr', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_type', 'brand', 'city')
    )
    op.create_table('enquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carpenter_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=True),
    sa.Column('client_phone', sa.Text(), nullable=True),
    sa.Column('room_type', sa.Text(), nullable=True),
    sa.Column('furniture_needed', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('room_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('share_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['carpenter_id'], ['carpenters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('enquiry_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('image_hash', sa.Text(), nullable=True),
    sa.Column('photo_type', sa.Text(), nullable=True),
    sa.Column('upload_order', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('furniture_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('material_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('material_cost', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('labour_cost', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('margin_pct', sa.NUMERIC(precision=4, scale=2), nullable=True),
    sa.Column('final_price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=False),
    sa.Column('carpenter_id', sa.UUID(), nullable=False),
    sa.Column('quote_number', sa.Text(), nullable=True),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('advance_requested', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('validity_days', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('viewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('razorpay_payment_link', sa.Text(), nullable=True),
    sa.Column('share_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['carpenter_id'], ['carpenters.id'], ),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('cv_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_hash', sa.Text(), nullable=False),
    sa.Column('enquiry_photo_id', sa.UUID(), nullable=True),
    sa.Column('room_width_mm', sa.Integer(), nullable=True),
    sa.Column('room_length_mm', sa.Integer(), nullable=True),
    sa.Column('room_height_mm', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.NUMERIC(precision=4, scale=2), nullable=True),
    sa.Column('detected_objects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_yolo_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_photo_id'], ['enquiry_photos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_hash')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('carpenter_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('expected_end_date', sa.DATE(), nullable=True),
    sa.Column('actual_end_date', sa.DATE(), nullable=True),
    sa.Column('progress_photos', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('carpenter_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['carpenter_id'], ['carpenters.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('carpenter_id', sa.UUID(), nullable=True),
    sa.Column('razorpay_payment_id', sa.Text(), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('payment_type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('paid_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['carpenter_id'], ['carpenters.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('jobs')
    op.drop_table('cv_results')
    op.drop_table('quotes')
    op.drop_table('furniture_items')
    op.drop_table('enquiry_photos')
    op.drop_table('enquiries')
    op.drop_table('material_prices')
    op.drop_table('furniture_catalogue')
    op.drop_table('carpenters')
    # ### end Alembic commands ###
